WatchShopSite/Areas/Admin/Controllers/AdminUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using ASP.NET_MVC5_Bootstrap3_3_1_LESS.Models;
using ASP.NET_MVC5_Bootstrap3_3_1_LESS.Controllers;
using WatchShopBUS.BUS;
using WatchShopConnect;
using WatchShopSite.Models;

namespace WatchShopSite.Areas.Admin.Controllers
{
    public class AdminUsersController : AccountController
    {
        //
        // GET: /Admin/AdminUsers/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DanhSachUser(int page=1)
        {
            var lst = NguoiDungBUS.GetAll(page);
            ViewBag.Current = User.Identity.GetUserId();
            return View(lst);
        }
        public ActionResult XoaTaiKhoan(NGUOIDUNG item)
        {
            item.DAXOA = true;
            NguoiDungBUS.XoaTaiKhoan(item);
            return View();
        }
        public ActionResult PhucHoiTaiKhoan(NGUOIDUNG item)
        {
            item.DAXOA = false;
            NguoiDungBUS.XoaTaiKhoan(item);
            return View();
        }

        public ActionResult PhanQuyen(string user,string per)
        {
            if (user != "")
            {
                string reper = "";
                if (per == "Admin")
                {
                    reper = "Member";
                }
                else
                {
                    if (per == "Member")
                    {
                        reper = "Admin";
                    }
                }
                UserManager.RemoveFromRole(UserManager.FindByName(user).Id, reper);
                UserManager.AddToRole(UserManager.FindByName(user).Id, per);
                ViewBag.pq = per;
            }
            return View();
        }
        public ActionResult frmCapNhat(NGUOIDUNG model)
        {
            NGUOIDUNG item = NguoiDungBUS.GetUser(model.UserID);
            IdentityUser user = UserManager.FindById(model.UserID);
            RegistorInf result = new RegistorInf { UserName=user.UserName, Address = item.DIACHI, BirthDate = item.NGAYSINH, Email = item.EMAIL, FullName = item.HOTEN, IdentityCart = item.CMND, PhoneNumber = item.SDT };
            return View(result);
        }
        public ActionResult CapNhatTaiKhoan(RegistorInf item)
        {
            if (item == null)
            {
                return RedirectToAction("DanhSachUser", new { page=1});
            }
            else
            {
                    var user = new WatchShopConnectDB().FirstOrDefault<AspNetUser>("select Id from AspNetUsers where UserName = '" + item.UserName + "'");
                    NGUOIDUNG nd = new NGUOIDUNG { UserID = user.Id, SDT = item.PhoneNumber, CMND = item.IdentityCart, HOTEN = item.FullName, EMAIL = item.Email, NGAYSINH = item.BirthDate, DIACHI = item.Address };    
                    NguoiDungBUS.CapNhatThongTin(nd);
                    return RedirectToAction("DanhSachUser", new { page=1});
            }
        }
	}
}

WatchShopSite/Areas/Admin/Views/AdminUsers/DanhSachUser.cshtml
@model PetaPoco.Page<WatchShopConnect.ViewUser>
@{ Layout = null; }
<div class="box">
    <div class="box-header with-border">
        <h2 class="box-title">Danh sách tài khoản</h2>
        <div class="box-tools pull-right">
            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            <div class="btn-group">
                <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown"><i class="fa fa-wrench"></i></button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                </ul>
            </div>
            <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Họ tên</th>
                                <th>Permission</th>
                                <th>Trạng thái</th>
                                <th>Thao tác</th>
                            </tr>
                        </thead>
                        <tbody id="dsSanPham">
                            @foreach (var item in Model.Items)
                            {
                                <tr>
                                    <td>@item.UserName</td>
                                    <td>@item.EMAIL</td>
                                    <td>@item.HOTEN</td>
                                    <td id="pq_@item.UserName">
                                        @if (item.Name == "Admin")
                                        {
                                            <span class="label label-success">Admin</span>
                                        }
                                        else
                                        {
                                            <span class="label label-danger">Member</span>
                                        }
                                    </td>
                                    <td id="tt_@item.UserName">
                                        @if (item.DAXOA == false)
                                        {
                                            <span class="label label-success">Đang hoạt động</span>
                                        }
                                        else
                                        {
                                            <span class="label label-danger">Đã xóa</span>
                                        }
                                    </td>
                                    <td>
                                        <div class="sparkbar" data-color="#00a65a" data-height="20">
                                            @if (ViewBag.Current != item.UserID)
                                            {
                                                @Ajax.ActionLink("Admin|", "PhanQuyen", new { user = item.UserName, per = "Admin" }, new AjaxOptions { UpdateTargetId = "pq_" + item.UserName });
                                                @Ajax.ActionLink("Member|", "PhanQuyen", new { user = item.UserName, per = "Member" }, new AjaxOptions { UpdateTargetId = "pq_" + item.UserName });
                                                if (ViewBag.current!=item.UserID)
                                                {
                                                    @Ajax.ActionLink("Xóa|", "XoaTaiKhoan", new WatchShopConnect.NGUOIDUNG { UserID = item.UserID }, new AjaxOptions { UpdateTargetId = "tt_" + item.UserName });
                                                }
                                                @Ajax.ActionLink("Phục hồi|", "PhucHoiTaiKhoan", new WatchShopConnect.NGUOIDUNG { UserID = item.UserID }, new AjaxOptions { UpdateTargetId = "tt_" + item.UserName });
                                            }
                                            @Ajax.ActionLink("Cập nhật", "frmCapNhat", new WatchShopConnect.NGUOIDUNG { UserID = item.UserID }, new AjaxOptions { UpdateTargetId = "ViewShow" })
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <div class="box-footer text-center">
                        <ul class="pagination">
                            @for (int i = 1; i <= Model.TotalPages; i++)
                            {
                                <li>@Ajax.ActionLink(i.ToString(), "DanhSachUser", "AdminUsers", new {page = i }, new AjaxOptions { UpdateTargetId = "ViewShow", InsertionMode = InsertionMode.Replace })</li>
                            }
                        </ul>
                        <!---Action link-->
                    </div>
                </div>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- ./box-body -->
</div><!-- /.box -->

WatchShopSite/Areas/Admin/Views/AdminUsers/PhanQuyen.cshtml
@{Layout = null;}
@if (ViewBag.pq == "Admin")
{
    <span class="label label-success">Admin</span>
}
else
{
    <span class="label label-danger">Member</span>
}

WatchShopSite/Areas/Admin/Views/AdminUsers/PhucHoiTaiKhoan.cshtml
@{ Layout = null;}
<span class="label label-success">Đang hoạt động</span>

WatchShopSite/Areas/Admin/Views/AdminUsers/XoaTaiKhoan.cshtml
@{ Layout = null;}
<span class="label label-danger">Đã xóa</span>

WatchShopSite/Areas/Admin/Views/AdminUsers/frmCapNhat.cshtml
@model WatchShopSite.Models.RegistorInf
@{ Layout = null;}
<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<div class="box">
    <div class="box-header with-border">
        <h2 class="box-title">Cập nhật tài khoản</h2>
        <div class="box-tools pull-right">
            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            <div class="btn-group">
                <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown"><i class="fa fa-wrench"></i></button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                </ul>
            </div>
            <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <script>
                function GetAlert(a) {
                    alert(a);
                }
            </script>
            <div class="col-md-12">
                <div class="table-responsive">
                    @Ajax.ActionLink("Trở về", "DanhSachUser", "AdminUsers" ,new AjaxOptions { UpdateTargetId = "ViewShow" }, new { @class = "btn btn-warning" })
                    <div class="row">
                        @using (Ajax.BeginForm("CapNhatTaiKhoan", "AdminUsers", new AjaxOptions { UpdateTargetId = "ViewShow", OnSuccess = "GetAlert('Cập nhật thành công')" }))
                        {
                            @Html.HiddenFor(m=>m.UserName)
                            <div class="col-md-7">
                                @Html.LabelFor(m => m.Email)
                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Email)
                            </div>
                            <div class="col-md-7">
                                @Html.LabelFor(m => m.BirthDate)
                                @Html.TextBoxFor(m => m.BirthDate, new { @class = "form-control",@type="date", @Value = Model.BirthDate.ToString("yyyy-MM-dd")})
                            </div>
                            <div class="col-md-7">
                                @Html.LabelFor(m => m.FullName)
                                @Html.TextBoxFor(m => m.FullName, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.FullName)
                            </div>
                            <div class="col-md-7">
                                @Html.LabelFor(m => m.IdentityCart)
                                @Html.TextBoxFor(m => m.IdentityCart, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.IdentityCart)
                            </div>
                            <div class="col-md-7">
                                @Html.LabelFor(m => m.Address)
                                @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Address)
                            </div>
                            <div class="col-md-7">
                                @Html.LabelFor(m => m.PhoneNumber)
                                @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control", type="number" })
                                @Html.ValidationMessageFor(m => m.PhoneNumber)
                            </div>
                            <div class="col-md-9" style="margin-top:10px">
                                <input type="submit" class="btn btn-success" value="Cập nhật tài khoản" />
                            </div>
                        }
                    </div>
                    <div class="box-footer text-center">
                        <!---Action link-->
                    </div>
                </div>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- ./box-body -->
</div><!-- /.box -->