WatchShopSite/Areas/Admin/Controllers/AdminNhaSanXuatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchShopBUS.BUS;
using WatchShopConnect;

namespace WatchShopSite.Areas.Admin.Controllers
{
    public class AdminNhaSanXuatController : Controller
    {
        //
        // GET: /Admin/AdminNhaSanXuat/

        public ActionResult DanhSachNhaSanXuat()
        {
            var data = NhaSanXuatBUS.GetAll();
            return View(data);
        }
        public ActionResult ThemNhaSanXuat(NHASANXUAT item)
        {
            if (item.MANHASANXUAT != null)
            {
                NhaSanXuatBUS.AddNewItem(item);
                return RedirectToAction("DanhSachNhaSanXuat");
            }
            else
            {
                return View();
            }
        }
        public ActionResult XoaNhaSanXuat(string MANSX)
        {
            NhaSanXuatBUS.DeleteItemByID(MANSX);
            return RedirectToAction("DanhSachNhaSanXuat");
        }
        public ActionResult PhucHoiNhaSanXuat(string MANSX)
        {
            NhaSanXuatBUS.PhucHoiNhaSanXuat(MANSX);
            return RedirectToAction("DanhSachNhaSanXuat");
        }
    }
}

WatchShopSite/Areas/Admin/Views/AdminNhaSanXuat/DanhSachNhaSanXuat.cshtml
@model IEnumerable<WatchShopConnect.NHASANXUAT>
@{ Layout = null; }
<div class="box">
    <div class="box-header with-border">
        <h2 class="box-title">Danh sách nhà sản xuất</h2>
        <div class="box-tools pull-right">
            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            <div class="btn-group">
                <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown"><i class="fa fa-wrench"></i></button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                </ul>
            </div>
            <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    @Ajax.ActionLink("Thêm nhà sản xuất", "ThemNhaSanXuat", "AdminNhaSanXuat", new AjaxOptions { UpdateTargetId = "ViewShow" }, new { @class="btn btn-success" })
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Mã nhà sản xuất</th>
                                <th>Tên nhà sản xuất</th>
                                <th>Đã xóa</th>
                                <th>Thao tác</th>
                            </tr>
                        </thead>
                        <tbody id="dsSanPham">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.MANHASANXUAT</td>
                                    <td>@item.TENNHASANXUAT</td>
                                    <td>
                                        @if (item.DAXOA==false)
                                        { 
                                        <span class="label label-success">Đang hoạt động</span>
                                        }
                                        else
                                        {
                                             <span class="label label-danger">Đã xóa</span>
                                        }
                                    </td>
                                    <td>
                                        <div class="sparkbar" data-color="#00a65a" data-height="20">
                                            @Ajax.ActionLink("Xóa", "XoaNhaSanXuat", new { MANSX=item.MANHASANXUAT }, new AjaxOptions { UpdateTargetId = "ViewShow" })|
                                            @Ajax.ActionLink("Phục hồi", "PhucHoiNhaSanXuat", new { MANSX = item.MANHASANXUAT }, new AjaxOptions { UpdateTargetId = "ViewShow" })
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                    <div class="box-footer text-center">
                        <!---Action link-->
                    </div>
                </div>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- ./box-body -->
</div><!-- /.box -->

WatchShopSite/Areas/Admin/Views/AdminNhaSanXuat/ThemNhaSanXuat.cshtml
@model WatchShopConnect.NHASANXUAT
@{Layout = null;}
<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<div class="box">
    <div class="box-header with-border">
        <h2 class="box-title">Thêm nhà sản xuất mới</h2>
        <div class="box-tools pull-right">
            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            <div class="btn-group">
                <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown"><i class="fa fa-wrench"></i></button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                </ul>
            </div>
            <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
        <script>
            function GetAlert(a)
            {
                alert(a);
            }
        </script>
            <div class="col-md-12">
                <div class="table-responsive">
                    @Ajax.ActionLink("Trở về", "DanhSachNhaSanXuat", "AdminNhaSanXuat", new AjaxOptions { UpdateTargetId = "ViewShow" }, new { @class="btn btn-warning" })
                    <div class="row">
                        @using (Ajax.BeginForm("ThemNhaSanXuat", "AdminNhaSanXuat", new AjaxOptions { UpdateTargetId = "ViewShow", OnSuccess="GetAlert('Thêm mới nhà sản xuất thành công')" }))
                        {
                            @Html.ValidationSummary(true)
                            <div class="col-md-3">
                                @Html.LabelFor(m => m.MANHASANXUAT)
                                @Html.TextBoxFor(m => m.MANHASANXUAT, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.MANHASANXUAT)
                            </div>
                            <div class="col-md-3">
                                @Html.LabelFor(m => m.TENNHASANXUAT)
                                @Html.TextBoxFor(m => m.TENNHASANXUAT, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.TENNHASANXUAT)
                            </div>
                            <div class="col-md-9" style="margin-top:10px">
                                <input type="submit" class="btn btn-success" value="Thêm nhà sản xuất" />
                            </div>
                        }
                    </div>
                    <div class="box-footer text-center">
                        <!---Action link-->
                    </div>
                </div>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- ./box-body -->
</div><!-- /.box -->