WatchShopSite/Controllers/BinhLuanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchShopBUS.BUS;
using WatchShopConnect;
using Microsoft.AspNet.Identity;

namespace WatchShopSite.Controllers
{
    public class BinhLuanController : Controller
    {
        //
        // GET: /BinhLuan/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DSBinhLuan(string masp,int page=1)
        {
            return View(BinhLuanBUS.GetCommentUserView(masp,page));
        }
        public ActionResult ThemBinhLuan(BINHLUAN bl)
        {
            bl.THOIGIAN = DateTime.Now;
            if (bl.NGUOIBINHLUAN!="" && bl.THONGTINBINHLUAN !="")
                BinhLuanBUS.ThemBinhLuan(bl);
            return RedirectToAction("DSBinhLuan", new { masp = bl.MASANPHAM, page = 1 });
        }
	}
}

WatchShopSite/Views/BinhLuan/DSBinhLuan.cshtml
@model PetaPoco.Page<WatchShopConnect.BINHLUAN>
@{Layout = null;}

<div class="row">
    @foreach (var item in Model.Items)
    {
        <div class="col-md-12" style="margin-bottom:20px">
            <div class="col-md-1">
                <img src="@Url.Content("~/Content/img/userimg.jpg")" class="img-responsive" />
            </div>
            <div class="col-md-11">
                <div class="row"><span style="color: #5e90da; font-size: 18px; font-weight: 600;">@item.NGUOIBINHLUAN</span></div>
                <div class="row" style="color: #7bd445;font-size:14px">
                    @item.THOIGIAN.ToString() 
                </div>
                <div class="row" style="color:white">
                    @item.THONGTINBINHLUAN
                </div>
            </div>
        </div>   
    }
    <div class="col-md-12" style="margin-bottom:20px">
        <ul class="pagination">
            @for (int i=1;i<=Model.TotalPages;i++)
            {
                <li>@Ajax.ActionLink(i.ToString(), "DSBinhLuan", "BinhLuan", new { masp = Model.Items[0].MASANPHAM, page = i }, new AjaxOptions { UpdateTargetId="BinhLuanList", InsertionMode=InsertionMode.Replace })</li>
            }
        </ul>
    </div>
</div>