WatchShopSite/Controllers/LoaiDayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchShopBUS.BUS;

namespace WatchShopSite.Controllers
{
    public class LoaiDayController : Controller
    {
        //
        // GET: /LoaiDay/

        public ActionResult dsLoaiDay()
        {
            return View(LoaiDayBUS.GetAll());
        }
        public ActionResult Detail(int id,int n=1)
        {
            var List = LoaiDayBUS.Detail(id,n);
            if (List.Items.Count()<=0)
            {
                return RedirectToAction("Index","Error");
            }
            return View(List);
        }
    }
}

WatchShopSite/Controllers/LoaiVoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchShopBUS.BUS;

namespace WatchShopSite.Controllers
{
    public class LoaiVoController : Controller
    {
        public ActionResult dsLoaiVo()
        {
            return View(LoaiVoBUS.GetAll());
        }
        [HttpGet]
        public ActionResult Detail(int id,int n=1)
        {
            var List = LoaiVoBUS.Detail(id,n);
            if (List.Items.Count() <= 0)
            {
                return RedirectToAction("Index", "Error");
            }
            return View(List);
        }
    }
}

WatchShopSite/Controllers/NhaSanXuatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchShopBUS.BUS;

namespace WatchShopSite.Controllers
{
    public class NhaSanXuatController : Controller
    {
        //
        // GET: /NhaSanXuat/

        public ActionResult DSNhaSanXuat()
        {
            return View(NhaSanXuatBUS.GetAllUserView());
        }
        [Route("/NhaSanXuat/Detail/{id}/{n}")]
        public ActionResult Detail(string id,int n=1)
        {
            var List = new PetaPoco.Page<WatchShopConnect.SP_VIEW>();
            var nsx = NhaSanXuatBUS.GetItemByID(id);
            List = NhaSanXuatBUS.GetDetail(id,n);
            if (List.Items.Count() <= 0)
            {
                return RedirectToAction("Index", "Error");
            }
            ViewBag.nsx = nsx.TENNHASANXUAT;
            return View(List);
        }
    }
}

WatchShopSite/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchShopBUS.BUS;
using WatchShopBUS.Models;
using WatchShopConnect;

namespace WatchShopSite.Controllers
{
    public class SanPhamController : Controller
    {
        //
        // GET: /SanPham/

        public ActionResult Index(string id)
        {
            SANPHAM sp = SanPhamBUS.GetItemByID_Admin(id);
            sp.LUOTXEM += 1;
            sp.Save();
            var data = SanPhamBUS.GetItemByID(id);
            if (data.MASANPHAM == null || data.MASANPHAM=="")
            {
                return RedirectToAction("Index", "Error");
            }
            return View(data);
        }
        public ActionResult SanPhamCungNhaSanXuat(string mansx)
        {
            return View(SanPhamBUS.getItemByNSXID(mansx));
        }
        public ActionResult TimSanPhamTheoGia(int min,int max,int n=1)
        {
            ViewBag.min = min;
            ViewBag.max = max;
            return View(SanPhamBUS.TimSanPhamTheoGia(min, max, n));
        }
        /// <summary>
        /// Trả về chi tiết sản phẩm cho khách hàng
        /// </summary>
        /// <returns></returns>
        public ActionResult ViewDetail()
        {
            return View();
        }
        public ActionResult dsSPSale()
        {
            return View(SanPhamBUS.GetItemSale(10));
        }
        public ActionResult ChuongTrinhGiamGia(int n=1)
        {
            var List = SanPhamBUS.GetAllItemSale(n);
            return View(List);
        }
        public ActionResult FormTimKiem()
        {
            ViewBag.NSX = NhaSanXuatBUS.GetAll().Where(m=>m.DAXOA==false);
            ViewBag.LoaiVo = LoaiVoBUS.GetAll();
            ViewBag.LoaiDay = LoaiDayBUS.GetAll();
            ViewBag.LoaiNangLuong = LoaiNangLuongBUS.GetAll();
            return View();
        }
        public ActionResult KetQuaTimKiem(TimKiemSP info,int n=1)
        {
            if (info.beginGia==null)
            {
                info.beginGia = 0;
            }
            if (info.endGia==null)
            {
                info.endGia = int.MaxValue;
            }
            var List = SanPhamBUS.Search(info);
            int numrows = List.Count();
            int rowperpage = 8;
            int pageNum = n;
            int ofset = (pageNum - 1) * rowperpage;
            if (numrows % rowperpage != 0)
            {
                ViewBag.maxPage = numrows / rowperpage + 1;
            }
            else
            {
                ViewBag.maxPage = numrows / rowperpage;
            }
            string urlstr = Request.Url.AbsoluteUri;
            int pos=urlstr.IndexOf("&n=");
            urlstr = pos >= 0 ? urlstr.Remove(pos) : urlstr;
            ViewBag.url = urlstr;
            return View(List.Skip(ofset).Take(rowperpage));
        }
        public ActionResult SanPhamMoiNhap()
        {
            return View(SanPhamBUS.SanPhamMoiNhap());
        }
        public ActionResult SanPhamMuaNhieuNhat()
        {
            return View(SanPhamBUS.SanPhamMuaNhieu());
        }
    }
}

WatchShopSite/Views/Shared/Partial1.cshtml
@using WatchShopSite.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/css/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/font-awesome.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/css/MyStyle.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Content/js/jquery.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/js/jquery.jcarousel.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/js/bootstrap.min.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
    <title>@ViewBag.Title</title>
</head>
<body style="background: url('@Url.Content("~/Content/img/texture.jpg")')">
    @RenderSection("featured", required: false)
    <nav class="navbar navbar-inverse" style="margin-bottom: 0px;">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#HeaderNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="HeaderNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @using (Html.BeginForm("KetQuaTimKiem", "SanPham", FormMethod.Get, new { style="margin-top:8px" }))
                        {
                            @Html.TextBox("TenSanPham", null, new { @class = "form-control", placeholder = "Nhập tên sản phẩm..." });
                        }
                    </li>
                    <li>
                        @Ajax.ActionLink("Giỏ hàng", "GioHang", "ShoppingCart", new AjaxOptions { UpdateTargetId="ViewShow"})
                    </li>
                    @Html.Partial("_LoginPartial")
                </ul>
            </div>
        </div>
    </nav>
    <!--LOGO BÊN TRÁI, VÀ THANH TÌM KIẾM BÊN PHẢI-->
    <div class="container-fluid">
        <div class="row" style="height: 150px; margin-top: 5px; background: url('@Url.Content("~/Content/img/xxx.jpg")')">
            <div class="col-md-2 col-md-offset-1" style="margin-top: 10px">
                <a href="#"><img src="@Url.Content("~/Content/img/Watches-logo.png")"></a>
            </div>
        </div>
    </div>
    <!--MENU-->
    <nav class="navbar navbar-default" style="background-color:rgba(34, 34, 34, 0); border-color: rgba(34, 34, 34, 0)">
        <div class="col-md-11 col-md-offset-1">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="Menu collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active" style=""><a href="~/Home">Trang chủ</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" href="#">
                            Năng lượng
                            <span class="caret"></span>
                        </a>
                        <ul class="Menulv2">
                            @Html.Action("dsLoaiNangLuong", "LoaiNangLuong")
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" href="#">
                            Loại dây
                            <span class="caret"></span>
                        </a>
                        <ul class="Menulv2">
                            @Html.Action("dsLoaiDay", "LoaiDay")
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" href="#">
                            Loại vỏ
                            <span class="caret"></span>
                        </a>
                        <ul class="Menulv2">
                            @Html.Action("dsLoaiVo","LoaiVo")
                        </ul>
                    </li>
                    <li>
                        <a href="~/SanPham/ChuongTrinhGiamGia">Chương trình giảm giá</a>
                    </li>
                    <li>
                        <a href="#" data-toggle="modal" data-target="#FormTimKiemNangCao">Tìm kiếm nâng cao</a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </nav>
    <!--BANNER SLIDER OR DANH SACH SAN PHAM SLIDER-->
    @Html.Action("dsSPSale","SanPham")
    <!--BODY-->
    <div class="container-fluid">
        <!--DANH MUC LOAI SAN PHAM WIDTH 3(BOOTSTRAP)-->
        <div class="col-md-2 ListType">
            @Html.Action("DSNhaSanXuat","NhaSanXuat")
            <div class="list-group" style="box-shadow: 0px 0px 20px #12abff">
                <a href="#" class="list-group-item" style="background: url('@Url.Content("~/Content/img/ii.png")') repeat-x;">Tìm kiếm theo giá</a>
                @Html.ActionLink("Dưới 1 triệu", "TimSanPhamTheoGia", "SanPham", new { min=0,max=1000000 },new { @class="list-group-item"})
                @Html.ActionLink("1 triệu đến 5 triệu", "TimSanPhamTheoGia", "SanPham", new { min=1000000,max=5000000 },new { @class="list-group-item"})
                @Html.ActionLink("5 triệu đến 10 triệu", "TimSanPhamTheoGia", "SanPham", new { min=5000000,max=10000000 },new { @class="list-group-item"})
                @Html.ActionLink("10 triệu đến 20 triệu", "TimSanPhamTheoGia", "SanPham", new { min=10000000,max=20000000 },new { @class="list-group-item"})
                @Html.ActionLink("20 triệu đến 50 triệu", "TimSanPhamTheoGia", "SanPham", new { min=20000000,max=50000000 },new { @class="list-group-item"})
                @Html.ActionLink("50 triệu đến 100 triệu", "TimSanPhamTheoGia", "SanPham", new { min=50000000,max=100000000 },new { @class="list-group-item"})
                @Html.ActionLink("Trên 100 triệu", "TimSanPhamTheoGia", "SanPham", new { min=100000000,max=int.MaxValue },new { @class="list-group-item"})
            </div>
        </div>
        <!--DANH SACH SAN PHAM WIDTH 9(BOOTSTRAP)-->
        <div id="ViewShow">
            <div id="CartIcon">
                <a data-ajax="true" data-ajax-mode="replace" data-ajax-update="#ViewShow" href="/ShoppingCart/GioHang">
                    <i class="fa fa-cart-plus" style="font-size: 24px;color: lightgreen;" aria-hidden="true"></i>
                    <span id="CartCount" style="font-size: 24px;color: lightgreen;"> @ShoppingCart.CountItem(Session["ShoppingCart"]).ToString()</span>
                </a>
            </div>
            @RenderBody()
        </div>
    </div>
    <footer>
        <h2>Website design by AnhDang</h2>
    </footer>
    <!--Form Tim Kiem Nang Cao-->
    @Html.Action("FormTimKiem","SanPham")
    <!--Ket Thuc Form Tim Kiem Nang Cao-->
    <script src="@Url.Content("~/Content/js/Function.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.8.2.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.24.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")"></script>
    @RenderSection("scripts", required: false)
</body>
</html>